# Generated by Django 5.2.5

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='支出發生的日期時間', verbose_name='支出時間')),
                ('amount', models.DecimalField(decimal_places=2, help_text='支出金額', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='支出金額')),
                ('item_name', models.CharField(help_text='支出項目名稱', max_length=200, verbose_name='支出項目')),
                ('category', models.CharField(choices=[('日常支出', '日常支出'), ('食材採購', '食材採購'), ('水電費', '水電費'), ('租金', '租金'), ('人工費', '人工費'), ('其他', '其他')], default='日常支出', max_length=20, verbose_name='支出類別')),
                ('notes', models.TextField(blank=True, help_text='支出說明或備註', max_length=500, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL, verbose_name='記錄人員')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='expenses_ex_date_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_ex_categor_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['recorded_by'], name='expenses_ex_recorde_123456_idx'),
        ),
    ]
