# Generated by Django 5.2.5 on 2025-09-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_date_17a2b2_idx',
            old_name='expenses_ex_date_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_fcaba7_idx',
            old_name='expenses_ex_categor_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_recorde_569ad6_idx',
            old_name='expenses_ex_recorde_123456_idx',
        ),
    ]
