# Generated by Django 4.2.7 on 2025-08-31 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名稱')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='模板說明')),
                ('template_type', models.CharField(choices=[('daily', '日報'), ('weekly', '週報'), ('monthly', '月報'), ('quarterly', '季報'), ('yearly', '年報'), ('custom', '自定義')], max_length=20, verbose_name='模板類型')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否為預設模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_created', to=settings.AUTH_USER_MODEL, verbose_name='建立人員')),
            ],
            options={
                'verbose_name': '報表模板',
                'verbose_name_plural': '報表模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='報表名稱')),
                ('report_type', models.CharField(choices=[('daily', '日報'), ('weekly', '週報'), ('monthly', '月報'), ('quarterly', '季報'), ('yearly', '年報'), ('custom', '自定義')], default='daily', max_length=20, verbose_name='報表類型')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('store_id', models.CharField(default='main_store', max_length=50, verbose_name='店面ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總銷售額')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總成本')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='淨利潤')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='利潤率(%)')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='報表備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL, verbose_name='建立人員')),
            ],
            options={
                'verbose_name': '報表',
                'verbose_name_plural': '報表',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_id', 'report_type'], name='reports_rep_store_i_346c14_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx'), models.Index(fields=['created_by', 'store_id'], name='reports_rep_created_3b848f_idx')],
            },
        ),
    ]
