# Generated by Django 4.2.7 on 2025-08-31 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='類別說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '成本類別',
                'verbose_name_plural': '成本類別',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供應商名稱')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='成本發生日期', verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=2, help_text='成本', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成本')),
                ('description', models.CharField(help_text='成本項目說明', max_length=200, verbose_name='說明')),
                ('category', models.CharField(choices=[('食材', '食材'), ('營運費用', '營運費用'), ('人工', '人工'), ('水電', '水電'), ('租金', '租金'), ('其他', '其他')], default='食材', max_length=20, verbose_name='成本類別')),
                ('store_id', models.CharField(default='main_store', help_text='未來擴展多店管理用', max_length=50, verbose_name='店面ID')),
                ('supplier', models.CharField(blank=True, help_text='供應商名稱', max_length=100, verbose_name='供應商')),
                ('invoice_number', models.CharField(blank=True, help_text='發票或收據號碼', max_length=50, verbose_name='發票號碼')),
                ('notes', models.TextField(blank=True, help_text='額外說明或備註', max_length=500, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs_recorded', to=settings.AUTH_USER_MODEL, verbose_name='記錄人員')),
            ],
            options={
                'verbose_name': '成本',
                'verbose_name_plural': '成本',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'store_id'], name='costs_cost_date_401f95_idx'), models.Index(fields=['store_id', 'date'], name='costs_cost_store_i_591323_idx'), models.Index(fields=['category', 'store_id'], name='costs_cost_categor_da4276_idx'), models.Index(fields=['supplier', 'store_id'], name='costs_cost_supplie_e798c1_idx')],
            },
        ),
    ]
