# Generated by Django 4.2.7 on 2025-08-31 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='類別說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '銷售類別',
                'verbose_name_plural': '銷售類別',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='銷售日期', verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=2, help_text='當日銷售總額', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='銷售金額')),
                ('description', models.CharField(blank=True, help_text='銷售情況說明', max_length=200, verbose_name='說明')),
                ('category', models.CharField(choices=[('堂食', '堂食'), ('外帶', '外帶'), ('外送', '外送'), ('其他', '其他')], default='堂食', max_length=20, verbose_name='銷售類別')),
                ('store_id', models.CharField(default='main_store', help_text='未來擴展多店管理用', max_length=50, verbose_name='店面ID')),
                ('notes', models.TextField(blank=True, help_text='額外說明或備註', max_length=500, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_recorded', to=settings.AUTH_USER_MODEL, verbose_name='記錄人員')),
            ],
            options={
                'verbose_name': '銷售額',
                'verbose_name_plural': '銷售額',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'store_id'], name='sales_sale_date_f25e10_idx'), models.Index(fields=['store_id', 'date'], name='sales_sale_store_i_fa4844_idx'), models.Index(fields=['category', 'store_id'], name='sales_sale_categor_1d1a45_idx')],
                'unique_together': {('date', 'store_id')},
            },
        ),
    ]
